name: Build APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Unzip project
        run: unzip "SalikFlasher_ReactNative (1).zip"
      - name: Show full structure
        run: find . -maxdepth 5 -not -path '*/node_modules/*' -not -path '*/.git/*'
      - name: Stop here
        run: exit 1
